Fix broken test
java.lang.ClassNotFoundException: org.apache.http.conn.SchemePortResolver

(cherry picked from commit 8c1801caef4d77c1f5cd8236fa39a763d23c44f1)